import type { Clinic } from '@/types'

export const clinics: Clinic[] = [
  {
    id: '1',
    slug: 'siming',
    name: '厦门思明能仁堂门诊部',
    address: '厦门市思明区湖滨南路8-2-1',
    phone: '0592-5156156',
    specialties: ['体质调理', '女性康养', '睡眠调理'],
    hours: '周一至周日 9:00-18:00',
    description: '能仁堂旗舰门诊部，由多位三甲医院退休主任级专家领衔坐诊，提供全方位中医诊疗服务。',
    type: 'clinic',
  },
  {
    id: '2',
    slug: 'hexiang',
    name: '厦门思明能仁堂和祥门诊部',
    address: '厦门市思明区禾祥西路268-5号',
    phone: '0592-2026676',
    specialties: ['余氏骨伤', '疼痛管理', '小儿推拿'],
    hours: '周一至周六 8:30-17:30',
    description: '以骨伤和疼痛管理为特色，传承余氏骨伤流派手法，深受周边居民信赖。',
    type: 'clinic',
  },
  {
    id: '3',
    slug: 'mingben',
    name: '厦门湖里能仁堂明本门诊部',
    address: '厦门市湖里区云顶北路1167号3楼',
    phone: '0592-5780578',
    specialties: ['肥胖四高', '结节调理', '体质调理'],
    hours: '周一至周五 9:00-17:00',
    description: '以代谢调理和结节调理为特色，提供个性化中医慢病管理方案。',
    type: 'clinic',
  },
  {
    id: '4',
    slug: 'hospital',
    name: '厦门集美能仁堂中医院',
    address: '厦门市集美区杏林街道杏锦路12号',
    phone: '0592-6662727',
    specialties: ['中医内科', '中医外科', '中医妇科', '针灸推拿', '康复疗养'],
    hours: '周一至周日 8:00-21:00',
    description: '二级中医院，功能齐全，由多位三甲医院退休主任级专家领衔，提供权威、精准、个性化的诊疗服务。',
    type: 'hospital',
  },
  {
    id: '5',
    slug: 'sanmen',
    name: '厦门湖里能仁堂第三门诊部',
    address: '厦门市湖里区岭南里47号',
    phone: '0592-2225120',
    specialties: ['中医全科', '中医康复', '艾灸理疗'],
    hours: '周一至周日 8:00-19:00',
    description: '服务湖里居民的综合中医门诊，中医康复和艾灸理疗广受好评。',
    type: 'clinic',
  },
  {
    id: '6',
    slug: 'pharmacy',
    name: '能仁堂大药房',
    address: '厦门市',
    phone: '',
    specialties: ['中药饮片', '中成药', '代煎服务'],
    hours: '周一至周日 8:00-21:00',
    description: '严选道地药材，提供中药饮片、中成药及专业代煎服务，品质保障。',
    type: 'pharmacy',
  },
  {
    id: '7',
    slug: 'food-therapy',
    name: '能仁堂药食同源门店（食养小屋）',
    address: '厦门市',
    phone: '',
    specialties: ['节气食养', '养生茶饮', '体质食疗'],
    hours: '周一至周日 9:00-18:00',
    description: '秉承"药食同源"理念，将中医食养智慧与现代营养科学融合，提供个性化食疗方案。',
    type: 'food-therapy',
  },
  {
    id: '8',
    slug: 'health-tech',
    name: '能仁堂健康科技公司',
    address: '厦门市',
    phone: '',
    specialties: ['健康科技', '自主专利', '产品研发'],
    hours: '周一至周五 9:00-18:00',
    description: '拥有多项自主专利的健康科技公司，致力于中医药健康产品的研发与创新。',
    type: 'health-tech',
  },
]
